### ISSUE TITLE
invalid class TRUNDLL 

### ISSUE THREAD

**Issue by DMFSouza** [totvs/tlpp-dyncall-samples#1]
Boa tarde, a algum tempo estou tentando utilizar o exemplo do Dyncall disponível no TDN mas sem sucesso...
Tentei utilizar logo quando foi divulgado e me foi apresentado o erro "invalid class TRUNDLL ", resolvi esperar mais um tempo e após atualizar para a 2310, atualizar o RPO do tlpp e afins sigo com o mesmo problema na hora que vai instanciar tRunDll():New me diz que a classe é invalida...
Poderia me auxiliar?
Esta é minha versão do appserver:
* Build: 64 bits
* SVN Revision: 41034
* Build Version: 20.3.2.5

**Comment by dansigolo** [comment]
Bom dia.

O Dyncall é um recurso novo que está em fase de desenvolvimento.
Ela será liberado apenas na versão 24.3.0.0 do TOTVS | Application Server e seu uso, por hora, estará liberado apenas para desenvolvedores TOTVS que possuírem chave de compilação.

Mais detalhes na nossa ágina do TDN: https://tdn.totvs.com/display/tec/DynCall

Até.
